export var projects = [
    {
        name:"Memory Reports",
        folder:"memoryreports",
        date:"2020/12/01",
        short_description:"Ticket system with real time notifications",
        description:"This is a project to solve support tickets on physical sites, this project implments real time notifications using webpushjs and recurrent notifications using pushjs on client side, is written using Vue JS for the frontend with Vuetify UI framework and NodeJS on the backend with MongoDB for data store.",
        full_description:"This is a project to solve support tickets on physical sites, this project implments real time notifications using webpushjs and recurrent notifications using pushjs on client side, is written using Vue JS for the frontend with Vuetify UI framework and NodeJS on the backend with MongoDB for data store.",
        url: "https://memoryreports.com/",
        cover:"",
        images:[

        ],
        repos:[
        ],
        private:true,
        technologies:[
            "Vue",
            "MongoDB",
            "NodeJS",
            "Flutter",
        ],
        notes:"",
        show:true,
    },
    {
        name:"IotIN",
        folder:"iotin",
        date:"2020/06/01",
        short_description: "Access control and assistance system",
        description: "Access control and assistance system build using a SOA oriented architecture that provides encrypted codes and facial recognition, the goal of this project is provide a secure, low cost and easy integration access control system to any company with the benefits of cutting edge technologies",
        full_description: "Access control system build using a SOA oriented architecture that provides encrypted codes and facial recognition, the goal of this project is provide a secure, low cost and easy integration access control system to any company with the benefits of cutting edge technologies",
        url: null,
        cover:"",
        repos: [
            "https://github.com/marco-gallegos/shaka",
        ],
        private:false,
        technologies:[
            "Python",
            "NodeJS",
            "Ionic",
            "Angular",
            "Vue",
            "AWSS3",
            "Raspberry",
            "Arduino",
            "Sqlite",
            "Mysql",
        ],
        notes:"This a multiple repository project and not all are public by now",
        show:true,
    },
    {
        name:"Electro Revolution",
        folder:"iotin",
        date:"2020/07/01",
        short_description:"",
        description: "Administrative platform inspired and required as a new version of a previous Microsoft Access administrative system.",
        full_description: "Administrative platform inspired and required as a new version of a previous Microsoft Access administrative system.",
        url: "http://administracion.ecsn.com.mx/",
        cover: "",
        repos: [
            "https://github.com/marco-gallegos/shaka",
        ],
        private:true,
        technologies:[
            "Laravel",
            "Vue",
            "Mysql",
        ],
        notes:"",
        show:false,
    },
    {
        name:"Foodex",
        folder:"foodex",
        date:"2018/12/01",
        short_description:"Dinning service Control",
        description: "Is a web platform to manage employees access and previous registration to the dining service, the goal is to digitize and automate this process to get a better result on nominal discounts and control excess food.",
        full_description: "Is a web platform to manage employees access and previous registration to the dining service, the goal is to digitize and automate this process to get a better result on nominal discounts and control excess food.",
        url: "https://comedor.grupoascencio.com.mx/",
        cover: "",
        repos: [
            "",
        ],
        private:true,
        technologies: [
            "Laravel",
            "Vue",
            "Mysql",
        ],
        notes:"",
        show:true,
    },
]