export var technologies = [
    {
        name:"Python",
        logo:"python.svg",
        url:"https://www.python.org/",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Laravel",
        logo:"laravel.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Vue",
        logo:"vue.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"React",
        logo:"react.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Golang",
        logo:"gopher.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Javascript",
        logo:"javascript.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"C++",
        logo:"c-plusplus.svg",
        url:"https://es.wikipedia.org/wiki/C%2B%2B",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"MongoDB",
        logo:"mongodb.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ],
    },
    {
        name:"Mysql",
        logo:"mysql.svg",
        url:"https://www.mysql.com/",
        known:true,
        proyectos:[
            {
                
            }
        ],
    },
    {
        name:"SQLServer",
        logo:"mssql.svg",
        url:"https://en.wikipedia.org/wiki/Microsoft_SQL_Server",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Postgres",
        logo:"postgresql.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ],
    },
    {
        name:"Sqlite",
        logo:"sqlite.svg",
        url:"",
        known:false,
        proyectos:[
            {
                
            }
        ],
    },
    {
        name:"ReactNative",
        logo:"expo.svg",
        url:"https://reactnative.dev/",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Flutter",
        logo:"flutter.svg",
        url:"https://flutter.dev/",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Java",
        logo:"java.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Docker",
        logo:"docker.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Php",
        logo:"php.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Redis",
        logo:"redis.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Hadoop",
        logo:"hadoop.svg",
        url:"",
        known:false,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Raspberry",
        logo:"raspberry.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Arduino",
        logo:"arduino.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"Linux",
        logo:"linux-tux.svg",
        url:"",
        known:true,
        proyectos:[
            {
                
            }
        ]
    },
    {
        name:"NodeJS",
        logo:"nodejs.svg",
        known:true,
        url:"https://nodejs.org/es/",
        proyectos:[
            {
            }
        ]
    },
    
    
    {
        name:"Ionic",
        logo:"ionic.svg",
        known:false,
        url:"",
        proyectos:[
            {
            }
        ]
    },
    {
        name:"Angular",
        logo:"angular.svg",
        known:false,
        url:"",
        proyectos:[
            {
            }
        ]
    },
    {
        name:"AWSS3",
        logo:"awss3.svg",
        known:false,
        url:"",
        proyectos:[
            {
            }
        ]
    },
    {
        name:"Git",
        logo:"github.svg",
        known:true,
        url:"",
        proyectos:[
            {
            }
        ]
    },
    {
        name:"Vuetify",
        logo:"vuetifyjs.svg",
        known:true,
        url:"",
        proyectos:[
            {
            }
        ]
    },
    {
        name:"Bootstrap",
        logo:"bootstrap.svg",
        known:true,
        url:"",
        proyectos:[
            {
            }
        ]
    },
];
